# Generated by Django 3.1.13 on 2021-12-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211204_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avator',
            field=models.CharField(default='/static/avator/default.png', max_length=255),
        ),
    ]
