# Generated by Django 3.1.13 on 2021-12-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_avator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avator',
            field=models.CharField(default='/static/avator/default.jpg', max_length=255),
        ),
    ]
